update delius config for contact log notifications
ministryofjustice/hmpps-interventions-service pull request #115
Opened 2021-02-23 09:53 UTC by tomsmyers

## What does this pull request do?

update delius config for contact log notifications

## What is the intent behind these changes?

get the 'referral sent' notification showing up in delius.

2021-02-23 17:02 UTC, mxco86 requested changes

2021-02-23 17:22 UTC, tomsmyers commented on helm_deploy/values-dev.yaml
> +  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_STAFFCODE: "CRSUAT"
should the team code match?

2021-02-23 17:25 UTC, mxco86 commented on helm_deploy/values-dev.yaml
> +  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_STAFFCODE: "CRSUAT"
No - team code is correct as it is

2021-02-23 17:26 UTC, mxco86 submitted a review, later dismissed

2021-02-24 08:37 UTC, tomsmyers commented on helm_deploy/values-dev.yaml
> +  COMMUNITYAPI_CONTACTNOTIFICATIONCONTEXT_STAFFCODE: "CRSUAT"
sorted, thanks.

2021-02-24 09:26 UTC, mxco86 approved these changes
👍

2021-02-24 09:31 UTC, sldblog approved these changes
👍 LGTM; could we leave a note on why the codes changed, please? (For me, it's important to know what external change has to be reflected in the future)

2021-02-24 09:38 UTC, tomsmyers commented
> 👍 LGTM; could we leave a note on why the codes changed, please? (For me, it's important to know what external change has to be reflected in the future)

paging @mxco86  for this

2021-02-24 09:38 UTC, merged

2021-02-24 09:40 UTC, mxco86 commented
> 👍 LGTM; could we leave a note on why the codes changed, please? (For me, it's important to know what external change has to be reflected in the future)

The codes have now been confirmed on the Delius side as-per this:https://github.com/ministryofjustice/hmpps-interventions-service/pull/115