rename 'city-of-london' pcc region from 'City of London' to 'London'
ministryofjustice/hmpps-interventions-service pull request #160
Opened 2021-03-24 14:50 UTC by tomsmyers

## What does this pull request do?

rename 'city-of-london' pcc region from 'City of London' to 'London'

## What is the intent behind these changes?

make the 'find' page more user friendly

2021-03-24 14:51 UTC, sldblog approved these changes
Could we also do this in https://github.com/ministryofjustice/hmpps-reference-data/blob/main/pcc-regions-for-probation-v0.csv, please?

2021-03-25 14:26 UTC, sldblog commented
I've asked around and the current proposal is:

- Remove City of London PCC
- Add Met Police PCC with the name of "London (Metropolitan Police)" and the ID used in https://data.police.uk/api/forces

I'll amend the PR here

2021-03-26 08:27 UTC, rgforsyth approved these changes

2021-03-26 11:44 UTC, rgforsyth requested changes
Version number on migration will need to be updated. Sorry

2021-03-26 11:51 UTC, sldblog commented
@rgforsyth Done!

2021-03-29 09:42 UTC, rgforsyth approved these changes
👍

2021-03-29 10:23 UTC, merged

2021-03-29 10:23 UTC, sldblog commented
🙇‍♂️ Thank you