Upgrade intervention service docker java 17
ministryofjustice/hmpps-interventions-service pull request #917
Opened 2022-04-04 14:45 UTC by kth13

## What does this pull request do?

- upgrades the intervention service to JDK17. Updates the docker image to use openjdk-17

## What is the intent behind these changes?

It is a technical debt to upgrade intervention service to latest jdk version.

2022-04-05 09:55 UTC, kth13 commented on Dockerfile
> +FROM openjdk:17-slim
I am not able to find the  **adoptopenjdk/openjdk17:alpine-jre** from the docker hub.What I found was adoptopenjdk was deprecated. I was checking other repositories and they were using openjdk:17-slim. That is the reason why I choose this version

2022-04-05 11:40 UTC, tomsmyers commented on Dockerfile
> +FROM openjdk:17-slim
awesome - fine with me. would still be good to see how it affects the size of the final build.

2022-04-05 11:41 UTC, tomsmyers approved these changes

2022-04-05 14:45 UTC, kth13 commented on Dockerfile
> +FROM openjdk:17-slim
The application sizes built with the following base images
eclipse-temurin:17.0.2_8-jre-focal ==> 289MB
alpine:3.15 ==> 349MB

2022-04-05 15:48 UTC, sldblog requested changes
CircleCI config also has some Java 11 references, eg.

https://github.com/ministryofjustice/hmpps-interventions-service/blob/f70506b5698ec56724021d0686126ae80298daca/.circleci/config.yml#L17

~~Unsure how to make sure that all jobs use the Java 17 executor~~

It looks like the "tag" can be given for the `hmpps/java` executor: https://github.com/ministryofjustice/hmpps-circleci-orb/blob/be1dbcd551d4e8771f026ced818bd38baad035aa/src/executors/java.yml#L3

Could those be updated, please?

2022-04-05 15:48 UTC, sldblog commented on Dockerfile
> +# force a rebuild of `apt-get update` below by invalidating the BUILD_NUMBER env variable on every commit
🙋‍♂️ This change is no longer needed (apk stayed below)

2022-04-06 09:48 UTC, sldblog commented on Dockerfile
> +FROM openjdk:17-slim
Do we save with the `openjdk17-jre-headless` package? That one doesn't install the sound and graphical libraries

2022-04-06 09:51 UTC, sldblog commented
Yeah, I think we will have to do something like this

https://github.com/ministryofjustice/hmpps-assess-risks-and-needs/blob/589df543dabc3d6b6c625b099e85d2b9d2be0b66/.circleci/config.yml#L13-L15

By default, the non-dockerised Java builds would run on an executor which has Java 11 so we could have a pass where Java 17 would fail

2022-04-06 10:13 UTC, sldblog commented
Please ignore the above -- I didn't see db39bb69b927423d343a1e8f2117c7fca82f7624 commit before I made the above comment about 17.0

2022-04-06 10:48 UTC, kth13 commented on Dockerfile
> +FROM openjdk:17-slim
alpine:3.15 ==> openjdk17-jre ==> 349MB
alpine:3.15 ==> openjdk17-jre-headless ==> 349MB

In terms of size, both are same

2022-04-06 10:56 UTC, sldblog commented on Dockerfile
> +FROM openjdk:17-slim
👍 that's weird, but ok

can we still switch to it, please? fewer dependencies mean fewer security CVEs

2022-04-06 14:01 UTC, kth13 commented on Dockerfile
> +FROM openjdk:17-slim
@sldblog , sure I will change to it

2022-04-07 11:19 UTC, sldblog approved these changes
👍 LGTM

To note, this should still produce JVM11-compatible bytecode as-is

2022-04-07 11:27 UTC, merged